### ISSUE TITLE
Upload to crates.io

### ISSUE THREAD

**Issue by rabite0** [AdnoC/sixel-rs#2]
It would be great if you could upload sixel-rs to crates.io, just like sixel-sys. I'm currently using it in hunter to show images/video frames. If you have no interest in working on this any more I could also do it myself, but I wanted to ask you before I do that, since it's your library.

**Comment by AdnoC** [comment]
This was something I had briefly worked on to get a handle on Rust and is very unfinished. Please go ahead.

Sorry for not responding sooner, github notifications have been spammed by my job and I haven't gotten around to handling them.
